name: limboscan
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.6+9

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.2.0
  svg_flutter: ^0.0.1
  flutter_svg: ^2.0.7
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.4.3
  pretty_qr_code: ^2.0.3
  flutter_native_splash: ^2.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  oktoast: ^3.3.1
  vibration: ^1.8.1
  url_launcher: ^6.1.14
  share_plus: ^7.1.0
  flutter_statusbarcolor_ns: ^0.5.0
  flutter_launcher_icons: ^0.13.1
  video_player: ^2.7.1
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/ilustrations/
    - assets/ilustrations/welcomevideo.mp4
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: assets/logos/appstore.png
  ios: appiconios
  image_path_ios: assets/logos/appstore.png
  remove_alpha_ios: true
